#{{ gitlab_config.projects | selectattr('name','equalto', target ) | map(attribute='project_id') | join(' ') }}
---
  - name: Create Gitlab project access token
    ansible.builtin.uri:
      url: "{{ gitlab_config.api_url }}/projects/{{ gitlab_config.projects | selectattr('name','equalto', target ) | map(attribute='project_id') | join(' ') }}/access_tokens"
      method: POST
      body_format: json
      status_code: [200, 201, 202]
      return_content: true
      headers:
        PRIVATE-TOKEN: "{{ gitlab_config.users | selectattr('username','equalto', user_name ) | map(attribute='user_api_token') | join(' ') }}"
        Content-Type: application/json
      body:
        name: "{{ item.name }}"
        scopes: "{{ item.scopes }}"
        expires_at: "{{ item.expires_at }}"
        access_level: "{{ item.access_level }}"   
    with_items: "{{ gitlab_config.projects | selectattr('name','equalto', target) | map(attribute='project_token') }}"
    no_log: false
    ignore_errors: true
#    changed_when: false
    register: reg

  - name: Set Gitlab project access token to variable
    set_fact:
      project_access_token: "{{ reg.results[0]['json']['token'] }}"