---
  - name: Create Gitlab project repository branches
    ansible.builtin.uri:
      url: "{{ gitlab_config.api_url }}/projects/{{ gitlab_config.projects | selectattr('name','equalto', target ) | map(attribute='project_id') | join(' ') }}/repository/branches"
      method: POST
      body_format: json
      status_code: [200, 201, 202]
      return_content: true
      headers:
        PRIVATE-TOKEN: "{{ gitlab_config.users | selectattr('username','equalto', user_name ) | map(attribute='user_api_token') | join(' ') }}"
        Content-Type: application/json
      body:
        branch: "{{ item.branch }}"
        ref: "{{ item.ref }}"
    with_items: "{{ gitlab_config.projects | selectattr('name','equalto', target ) | map(attribute='branches_project') }}"
    ignore_errors: true
    changed_when: false