apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-nginx-static-html-demo
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-nginx-static-html-demo
  template:
    metadata:
      namespace: demo-app
      labels:
        app: kubernetes-nginx-static-html-demo
    spec:
      containers:
        - name: static-html
          image: __VERSION__
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http-app
              protocol: TCP
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-nginx-static-html-demo
  namespace: demo-app
spec:
  selector:
    app: kubernetes-nginx-static-html-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30080
  type: NodePort