---
  - block:
      - name: Installing docker
        shell: |
          curl -fsSL get.docker.com -o get-docker.sh
          chmod +x get-docker.sh
          ./get-docker.sh
    rescue:
      - name: Installing docker
        apt:
          package: "docker"
          state: present
          update_cache: yes

  - name: Add the current user to docker group
    user: name=vagrant append=yes groups=docker

  - name: Install docker-compose
    apt:
      package: "docker-compose"
      state: present
      update_cache: yes

  - name: Install docker.py
    pip:
      name: docker
      state: present

  - name: Start docker service
    service:
      name: docker
      state: restarted
      enabled: yes
